version: '2'

services:
  percona:
    image: docker.io/percona:psmdb-5.0.8
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=dbPassword123456
      # Remove host variable to allow %
      #- MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=DB
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '12799:8000'
    environment:
      - BROADCAST_DRIVER=predis
      - CACHE_DRIVER=predis
      - FILESYSTEM_DISK=predis
      - QUEUE_CONNECTION=predis
      - SESSION_DRIVER=predis
      - SESSION_LIFETIME=120
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=DB
      - DB_PASSWORD=dbPassword123456
    volumes:
      - './my-project:/app'
    depends_on:
      - percona
